class_name Player
extends CharacterBody2D

# How far past the body the rake sweeps. The gather sensor is a separate, larger
# Area2D on collision layer 2; seaweed watches for THAT rather than the player's
# body, so reach can grow with upgrades without changing the hitbox that drunk
# tourists collide with.
const BASE_REACH := 12.0

# The source art already faces LEFT, so the sprite must be mirrored when moving
# RIGHT -- not the other way round. Flip this if the artwork is ever redrawn.
const ART_FACES_LEFT := true

const WALK_FPS := 9.0

# Every player texture is authored at half density and drawn at exactly 2x.
# Deriving the scale from an art size instead invites non-uniform scaling the
# moment a texture's aspect differs from its art box -- which it now does, since
# the rake states need a wider box to hold the tool.
const ART_SCALE := 2.0

# Draws the gather area as a translucent box. A bring-up aid from before there
# was art -- against finished sprites it reads as a rendering bug, so it is off
# by default. Flip it in the inspector when tuning reach.
@export var debug_reach := false

# Rain jacket: the same walking art with its hi-vis recoloured, done in a shader
# rather than as a second set of textures. Covers every on-foot state including
# the wading poses, and any walking art added later gets it for free.
const JACKET_SHADER := preload("res://shaders/hue_swap.gdshader")

# Stats -- these are what upgrades mutate. Everything the player buys should
# change one of these numbers and nothing else.
var base_speed := 130.0
var speed_mult := 1.0
var capacity := 5
var gather_interval := 0.7   # seconds per unit of seaweed
var has_rain_jacket := false
var has_waders := false
var has_sand_tires := false
var on_vehicle := false
var can_enter_deep := false

# True while standing in the loading bay. Nothing bad can touch you there.
var in_safe_zone := false

# Carried load is tracked two ways: count (against capacity) and credit value
# (deep kelp is worth 3x per slot, which is what makes deep water worth it).
var carried := 0
var carried_value := 0

# Zone boundaries, handed over by Game so the player knows where water starts.
var shallow_y := 400.0
var deep_y := 560.0
var min_y := 270.0             # top of the beach strip
var max_y := 548.0
var bay_x := 268.0             # right of this, the loading bay driveway opens up
var bay_min_y := 220.0

# Drop a PNG onto any of these in the Inspector and that upgrade state starts
# drawing the sprite instead of the placeholder rectangle. Empty slots keep the
# rectangle, so art can land one state at a time.
# Four-frame walk cycles, generated by tools/make_walk_frames.py. Frame 0 is the
# standing pose; the rest only play while moving.
@export var tex_bare: Array[Texture2D]
@export var tex_rake: Array[Texture2D]
@export var tex_backpack: Array[Texture2D]
@export var tex_tractor: Array[Texture2D]
@export var tex_hopper: Array[Texture2D]

# Rear views, used when moving AWAY from the camera. Every state has one: the
# whole cast is drawn three-quarter and mirrored for left/right, so the rear
# views are three-quarter too and the same flip covers both diagonals.
@export var tex_bare_back: Array[Texture2D]
@export var tex_rake_back: Array[Texture2D]
@export var tex_backpack_back: Array[Texture2D]
@export var tex_tractor_back: Array[Texture2D]
@export var tex_hopper_back: Array[Texture2D]

# Poses for the shallows: chest-up on foot, cut at the axle on a vehicle.
# Empty sets simply fall back to the dry art.
@export var tex_bare_wade: Array[Texture2D]
@export var tex_bare_wade_back: Array[Texture2D]
@export var tex_rake_wade: Array[Texture2D]
@export var tex_rake_wade_back: Array[Texture2D]
@export var tex_backpack_wade: Array[Texture2D]
@export var tex_backpack_wade_back: Array[Texture2D]

# Vehicles wade too -- cut at the axle line, wheels below the surface.
@export var tex_tractor_wade: Array[Texture2D]
@export var tex_tractor_wade_back: Array[Texture2D]
@export var tex_hopper_wade: Array[Texture2D]
@export var tex_hopper_wade_back: Array[Texture2D]

# How far up the joystick must point before the rear view takes over. Generous,
# so a mostly-sideways drift keeps the side view rather than flickering.
const BACK_THRESHOLD := 0.45

var reach := BASE_REACH

var joystick: Joystick
var game   # left untyped on purpose so we can read game.storm_active

var _stun := 0.0
var _facing_left := false
var _frames: Array[Texture2D] = []
var _frames_side: Array[Texture2D] = []
var _frames_back: Array[Texture2D] = []
var _frames_wade: Array[Texture2D] = []
var _frames_wade_back: Array[Texture2D] = []
var _facing_back := false
var _jacket_mat: ShaderMaterial
var _jacket_owned := false
var _anim_t := 0.0
var _anim_frame := -1

@onready var _sprite: ColorRect = $Visual
@onready var _sprite2d: Sprite2D = $Sprite
@onready var _shape: CollisionShape2D = $Shape
@onready var _gather_shape: CollisionShape2D = $GatherArea/Shape
@onready var _gather_vis: ColorRect = $ReachVisual


func _ready() -> void:
	# The GatherArea in the scene is on collision layer 2 and monitorable but
	# not monitoring: seaweed watches it, it watches nothing.
	_jacket_mat = ShaderMaterial.new()
	_jacket_mat.shader = JACKET_SHADER
	_jacket_mat.set_shader_parameter("enabled", false)
	_sprite2d.material = _jacket_mat

	set_body(Vector2(24, 24), Vector2(48, 48), Color(0.95, 0.78, 0.35))
	_sprite2d.flip_h = ART_FACES_LEFT


func set_body(hit: Vector2, art: Vector2, c: Color,
		frames: Array[Texture2D] = [],
		back_frames: Array[Texture2D] = [],
		wade_frames: Array[Texture2D] = [],
		wade_back_frames: Array[Texture2D] = []) -> void:
	# Collision and artwork are deliberately different sizes. The hitbox stays
	# where it was tuned; the sprite is drawn larger so that at half-density it
	# has enough pixels to read. A sprite overhanging a tighter hitbox is
	# standard practice and feels more forgiving, not less fair.
	(_shape.shape as RectangleShape2D).size = hit
	_sprite.size = art
	_sprite.position = -art / 2.0
	_sprite.color = c

	# Frames win over the placeholder. Scale comes from frame 0, so every frame
	# in a cycle must be the same size.
	_frames_side = frames
	_frames_back = back_frames
	_frames_wade = wade_frames
	_frames_wade_back = wade_back_frames
	_facing_back = false
	_frames = frames
	var has_art: bool = not _frames.is_empty() and _frames[0] != null
	_sprite2d.visible = has_art
	_sprite.visible = not has_art

	if has_art:
		_anim_t = 0.0
		_anim_frame = -1
		_show_frame(0)
		_sprite2d.scale = Vector2(ART_SCALE, ART_SCALE)

	# Grab area is the HITBOX plus reach on every side -- driven by collision,
	# not by how big the drawing happens to be.
	var g := hit + Vector2(reach, reach) * 2.0
	(_gather_shape.shape as RectangleShape2D).size = g
	_gather_vis.size = g
	_gather_vis.position = -g / 2.0
	_gather_vis.visible = debug_reach


func set_jacket(on: bool) -> void:
	_jacket_owned = on
	_apply_jacket()


func _apply_jacket() -> void:
	# Re-evaluated every time the frame set changes, not just on purchase.
	# Deciding this once at buy time left ordering holes, and the machines carry
	# yellow-green pixels of their own -- the driver's vest, the hopper rim and
	# the load itself -- so a stray enable recoloured the seaweed.
	if _jacket_mat != null:
		_jacket_mat.set_shader_parameter("enabled", _jacket_owned and not on_vehicle)


func in_water() -> bool:
	return position.y >= Zones.SHALLOW_TOP


func _current_set() -> Array[Texture2D]:
	# Wading wins over facing: chest-deep in the shallows, the stride is not
	# visible anyway, so a rear wade pose is only used when one exists.
	if in_water() and not _frames_wade.is_empty():
		if _facing_back and not _frames_wade_back.is_empty():
			return _frames_wade_back
		return _frames_wade
	if _facing_back and not _frames_back.is_empty():
		return _frames_back
	return _frames_side


func _face_camera(dir: Vector2) -> void:
	if dir.y < -BACK_THRESHOLD:
		_facing_back = true
	elif dir.y > BACK_THRESHOLD:
		_facing_back = false


func _refresh_set() -> void:
	var want := _current_set()
	if want.is_empty() or want == _frames:
		return
	_frames = want
	_anim_frame = -1
	_show_frame(int(_anim_t) % max(1, _frames.size()))
	_apply_jacket()


func _show_frame(i: int) -> void:
	if i == _anim_frame or _frames.is_empty():
		return
	_anim_frame = i
	_sprite2d.texture = _frames[i % _frames.size()]


func _tick_walk(delta: float, moving: bool) -> void:
	if _frames.size() < 2:
		return
	if not moving:
		# Standing still settles on the neutral pose rather than freezing
		# mid-stride, which looks like a dropped frame.
		_anim_t = 0.0
		_show_frame(0)
		return
	_anim_t += delta * WALK_FPS
	_show_frame(int(_anim_t) % _frames.size())


func current_speed() -> float:
	var s := base_speed * speed_mult

	# The storm is the rain jacket's whole reason to exist: without it you
	# slow to a crawl exactly when there is the most seaweed to collect.
	if game != null and game.storm_active and not has_rain_jacket:
		s *= 0.55

	# Water drags, hard. Wading the shallows bare-legged costs you 70% of your
	# speed -- enough that reaching the seaweed out there is not worth it until
	# the waders are bought. Deep water is heavy going even kitted out, but by
	# the time you can get there the waders are already a prerequisite.
	if position.y >= deep_y:
		s *= 0.72
	elif position.y >= shallow_y:
		if on_vehicle:
			# Road tyres bog down in wet sand. Sand Tires is to the tractor what
			# the waders are on foot: the shallows stay reachable but slow until
			# you pay for them.
			s *= 1.0 if has_sand_tires else 0.45
		else:
			s *= 1.0 if has_waders else 0.30

	return s


func is_full() -> bool:
	return carried >= capacity


func add_seaweed(n: int, value: int) -> void:
	var room: int = capacity - carried
	var taken: int = min(n, room)
	if taken <= 0:
		return
	carried += taken
	carried_value += value * taken


func dump() -> int:
	var v := carried_value
	carried = 0
	carried_value = 0
	return v


func get_hit() -> void:
	if _stun > 0.0:
		return
	if in_safe_zone:
		return
	_stun = 0.9

	# A tourist takes EVERYTHING. No upgrade softens this -- a full hopper of
	# deep kelp is gone in one collision, which is what keeps the late game from
	# turning into a victory lap.
	var lost_units := carried
	var lost_value := carried_value
	carried = 0
	carried_value = 0

	if game != null:
		game.on_player_hit(lost_units, lost_value, global_position)


func _physics_process(delta: float) -> void:
	if _stun > 0.0:
		_stun -= delta
		velocity = Vector2.ZERO
		modulate = Color(1, 1, 1, 0.45) if int(_stun * 12.0) % 2 == 0 else Color(1, 1, 1, 1)
		if _stun <= 0.0:
			modulate = Color(1, 1, 1, 1)
		return

	var dir: Vector2 = joystick.direction if joystick != null else Vector2.ZERO
	velocity = dir * current_speed()
	move_and_slide()

	# One sprite serves both directions. The deadzone means drifting straight up
	# or down doesn't flip the sprite back and forth on tiny x jitter.
	if absf(dir.x) > 0.25:
		var want_left := dir.x < 0.0
		if want_left != _facing_left:
			_facing_left = want_left
			# Mirror only when the desired facing differs from how it was drawn.
			_sprite2d.flip_h = (_facing_left != ART_FACES_LEFT)

	_face_camera(dir)
	_refresh_set()
	_tick_walk(delta, dir.length() > 0.05)

	position.x = clampf(position.x, 16.0, 344.0)

	# The loading bay is a driveway cut into the hotel grounds on the right, so
	# the player can go further up the screen there than anywhere else.
	var top := bay_min_y if position.x > bay_x else min_y
	position.y = clampf(position.y, top, max_y)
